### ISSUE TITLE
Use voxelized geometry solution between two arbitrarily defined points

### ISSUE THREAD

**Issue by damianjilk2** [damianjilk2/Deterministic-Radiation-Transport-Approximations#22]
Apply the 1-d toy problem with voxelized geometry and a voxelized solution <del>and use the capability between center points of voxels</del>. The current implementation starts at the left side of the start voxel and goes until the left side of the end voxel. <del>Alter this calculation to look at the center of the voxels when computing. </del>

New scope: in order to more easily validate/verify. Work from some arbitrarily defined point in one voxel to some arbitrarily defined point in another voxel (possibly the same voxel). This should primarily affect the calculation of tau.

Additionally update tester methods for new expected output.

**Comment by gonuke** [comment]
I think this is just a special case of #23 where your "sampled" points are just the center points.  It probably doesn't make sense to do a special case for just center points.

**Comment by gonuke** [comment]
Or better, replace this (or redefine it) as an issue to do one arbitrary point in `i` to one arbitrary point in `j` and then let #23 focus on the sampling/averaging part.

**Comment by damianjilk2** [comment]
An issue I am encountering when working on this feature is determining the shape of the matrices. 

The goal as described in the Neutronics Theory doc states we are given a voxelized geometry and return a voxelized solution. When considering an arbitrary location within a voxel, I am not certain how to maintain a voxelized solution. 

Is the expected solution one value depicting the flux going from the start location to the end location?

**Comment by damianjilk2** [comment]
An update from Slack convos: limited changes should be made other than within the tau calculation. The near term step is to move point 1 away from the left edge of voxel 1 and move point 2 away from the left edge of voxel 2, and figure out a way to determine tau. Future steps will include sampling points within the voxel and averaging to approximate the integrals described in Lewis and Miller.
